name: CI 
on: 
  push: 
    branches: [main] 
  pull_request: 
    branches: [main] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or the version you need
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Verify Java installation
        run: java -version
      - name: Set JAVA_HOME environment variable
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      - name: Cache files 
        uses: actions/cache@v4
        with: 
            path: | 
                ~/.sonar 
            key: ${{ runner.os }}-sonar 
            restore-keys: ${{ runner.os }}-sonar      
      - name: Download SonarScanner CLI version 5.0.1
        run: |
          SCANNER_VERSION=5.0.1.3006
          curl -L -o sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SCANNER_VERSION-linux.zip"
          unzip sonar-scanner.zip
          echo "SONAR_SCANNER_HOME=$PWD/sonar-scanner-$SCANNER_VERSION-linux" >> $GITHUB_ENV
          echo "$SONAR_SCANNER_HOME/bin" >> $GITHUB_PATH
      - name: Run Codescan On Push 
        if: github.event_name == 'push' 
        uses: codescan-io/codescan-scanner-action@2.0
        with: 
          codeScanUrl: https://preview.codescan.io/
          organization: nkar
          projectKey: test-git-1
          login: squ_6e202e8f5c86bc80dff610ad292677b55169b95e
          failOnRedQualityGate: false 
          generateSarifFile: true
          args: | 
            sonar.java.binaries=.
      - name: Run Codescan On PR 
        if: github.event_name == 'pull_request' 
        uses: codescan-io/codescan-scanner-action@prerelease-test
        with: 
          codeScanUrl: https://preview.codescan.io
          organization: nkar
          projectKey: test-git-1
          login: squ_6e202e8f5c86bc80dff610ad292677b55169b95e
          scanChangedFilesOnly: true 
          failOnRedQualityGate: false
          args: | 
            sonar.pullrequest.branch=${{github.head_ref}} 
            sonar.pullrequest.base=${{github.base_ref}} 
            sonar.pullrequest.key=${{github.event.number}} 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
            name: codescan.sarif
            path: codescan.sarif 
 
